site_name: Combine
repo_name: GitHub
repo_url: https://github.com/kcormi/HiggsAnalysis-CombinedLimit
edit_uri: edit/main/docs

nav:
        - Home: index.md
        - What Combine Does:
            - Intro: how_combine_works/introduction.md
            - Model: how_combine_works/model_and_likelihood.md
            - Fitting Concepts: how_combine_works/fitting_concepts.md
            - Statistical Tests: how_combine_works/statistical_tests.md
        - Setting up the analysis:
          - "Preparing the datacard": part2/settinguptheanalysis.md
          - "Physics models": part2/physicsmodels.md
          - "Automatic MC statistical uncertainties": part2/bin-wise-stats.md
        - Running combine:
          - "Running the tool":           part3/runningthetool.md
          - "Common statistical methods": part3/commonstatsmethods.md
          - "Advanced use cases":         part3/nonstandard.md
          - "Simplified Likelihoods":     part3/simplifiedlikelihood.md
          - "Unfolding & regularization": part3/regularisation.md
          - "Validating datacards":       part3/validation.md
          - "Debugging fit failures":     part3/debugging.md
        - Links & FAQ: part4/usefullinks.md
        - Tutorials:
          - "RooFit Basics":              part5/roofit.md
          - "Exercise: main features":    part5/longexercise.md
          - "Solutions to long exercise": part5/longexerciseanswers.md
          - "Exercise: parametric fit":   tutorial2023/parametric_exercise.md

theme:
        name: cinder
        include_sidebar: true
        highlightjs: true

extra_css:
  - "mystyle.css"

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

markdown_extensions:
        - pymdownx.arithmatex
        - pymdownx.details
        - pymdownx.blocks.details
        - admonition
