name: build
on:
  push:
    branches:
      - docs_test_deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs pymdown-extensions
      - run: mkdocs gh-deploy --force --clean --verbose
