name: Docs

on:
  workflow_dispatch:
  push:
    branches:
      - docs_test_deploy

jobs:
  docs:
    runs-on: ubuntu-latest
    name: Build and deploy test docs

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Build documentation
      run: |
        python3 -m pip install mkdocs pymdown-extensions mkdocs-material mike
        #mkdocs build --verbose --clean
        git fetch origin gh-pages --depth=1
        git config user.name ci-bot
        git config user.email ci-bot@example.com
        mike deploy latest --push
    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site

